---
- name: Install kube-prometheus-stack and prometheus-msteams
  hosts: azure_vms
  become: true
  tasks:
    - name: Create monitoring namespace
      command: kubectl create namespace monitoring
      ignore_errors: true

    - name: Add prometheus-community Helm repository
      command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      ignore_errors: true

    - name: Add prometheus-msteams Helm repository
      command: helm repo add prometheus-msteams https://prometheus-msteams.github.io/helm-charts
      ignore_errors: true

    - name: Update Helm repositories
      command: helm repo update

    - name: Install kube-prometheus-stack
      command: helm upgrade -i kube-prometheus prometheus-community/kube-prometheus-stack -n monitoring -f values.yaml

    - name: Install prometheus-msteams
      command: helm upgrade --install prometheus-msteams --namespace monitoring -f config.yaml prometheus-msteams/prometheus-msteams
