---
- name: Setup MongoDB Replica Set on Minikube
  hosts: azure_vms
  become: true
  tasks:
    - name: Apply headless service
      command: kubectl apply -f auto-testing-api/service.yaml

    - name: Apply stateful set
      command: kubectl apply -f auto-testing-api/stateful-set.yaml

    - name: Wait for deployment completion
      pause:
        minutes: 1

    - name: Connect to MongoDB pod
      command: kubectl exec -it -n mongo mongod-0 -c mongod-container -- bash
      args:
        creates: "failed"
        register: pod_shell

    - name: Print error log if failed to connect to pod
      debug:
        var: pod_shell.stderr_lines
      when: pod_shell.rc != 0

    - name: Connect to MongoDB shell
      command: mongosh
      args:
        stdin: |
          use admin
          rs.initiate({ _id: "MainRepSet", version: 1, members: [ { _id: 0, host: "mongod-0.mongo-service.mongo.svc.cluster.local:27017" }, { _id: 1, host: "mongod-1.mongo-service.mongo.svc.cluster.local:27017" }, { _id: 2, host: "mongod-2.mongo-service.mongo.svc.cluster.local:27017" } ]})

    - name: Execute rs.status() and log the output
      command: mongosh
      args:
        stdin: |
          use admin
          rs.status()
      register: rs_status

    - name: Print rs.status() output
      debug:
        var: rs_status.stdout_lines
