- name: Apply MongoDB Stateless Set
  hosts: azure_vms
  become: true
  tasks:
    - name: Create directories if they do not exist
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      loop:
        - /opt/services
        - /opt/services/mongo-api-stateful-set

    - name: Copy files to remote server
      copy:
        src: "/home/cicd/workspace/cicd-assets/mongo-api-stateful-set/"
        dest: "/opt/services/mongo-api-stateful-set"
        mode: '0644'

    - name: Apply namespace
      command: kubectl apply -f /opt/services/mongo-api-stateful-set/namespace.yaml

    - name: Apply headless service
      command: kubectl apply -f /opt/services/mongo-api-stateful-set/service.yaml

    - name: Apply stateful set
      command: kubectl apply -f /opt/services/mongo-api-stateful-set/stateful-set.yaml
