apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-script
  namespace: mongo
data:
  mongodb-script-initiate.sh: |
    #!/bin/bash
    mongosh --eval '
    rs.initiate({ _id: "MainRepSet", version: 1, members: [ { _id: 0, host: "mongod-0.mongo-service.mongo.svc.cluster.local:27017" }, { _id: 1, host: "mongod-1.mongo-service.mongo.svc.cluster.local:27017" }, { _id: 2, host: "mongod-2.mongo-service.mongo.svc.cluster.local:27017" } ] });
    rs.status();
    '

  mongodb-script-createuser.sh: |
    #!/bin/bash
    mongosh --eval '
    db.getSiblingDB("admin").createUser({ user: "root", pwd: "example", roles: [ { role: "root", db: "admin" } ] });
    '

