apiVersion: v1
kind: Secret
metadata:
  name: auto-testing-api-secret
  namespace: api
type: Opaque
data:
  DB_USER: cm9vdA==  # base64-encoded value for "root"
  DB_PASS: ZXhhbXBsZQ==  # base64-encoded value for "example"
