apiVersion: v1
kind: Service
metadata:
  name: auto-testing-api-service
  namespace: api
spec:
  selector:
    app: auto-testing-api
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
