version: "3.5"
services:
  db_master:
    image: mysql:8.0.30
    container_name: "db_master"
    restart: unless-stopped
    ports:
      - 3307:3306
    volumes:
      - ./master/data:/var/lib/mysql
      - ./master/master.cnf:/etc/my.cnf
    #env_file: ./master/.env.master
    environment:
      # - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      # - MYSQL_USER=${MYSQL_USER}
      # - MYSQL_DATABASE=${MYSQL_DATABASE}
      # - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=cicd@123
      - MYSQL_USER=cicd
      - MYSQL_DATABASE=my_database
      - MYSQL_PASSWORD=cicd@123
    networks:
      - mynetwork
  db_slave:
    image: mysql:8.0.30
    container_name: "db_slave"
    restart: unless-stopped
    depends_on:
      - db_master
    ports:
      - 3308:3306
    volumes:
      - ./slave/data:/var/lib/mysql
      - ./slave/slave.cnf:/etc/my.cnf
    #env_file: ./slave/.env.slave
    environment:
      - MYSQL_ROOT_PASSWORD=cicd@123
      - MYSQL_USER=cicd
      - MYSQL_DATABASE=my_database
      - MYSQL_PASSWORD=cicd@123
    networks:
      - mynetwork
networks:
  mynetwork:
# volumes:
#   /opt/services/mysql/slave/data:
#   /opt/services/mysql/master/data: