# version: '3'
# services:
#   mysql-master:
#     image: mysql:8.0.33
#     container_name: mysql-master
#     restart: always
#     env_file: ./master/.env.master
#     cap_add:
#       - all
#     environment:
#       - TZ:${TZ}
#       - MYSQL_DATABASE:${MYSQL_DATABASE}
#       - MYSQL_USER:${MYSQL_USER}
#       - MYSQL_PASSWORD:${MYSQL_PASSWORD}
#       - MYSQL_ROOT_PASSWORD:${MYSQL_PASSWORD}
#     ports:
#       - "3307:3306"
#     volumes:
#       - ./master/data:/var/lib/mysql
#       #- ./master/my.cnf:/etc/my.cnf
#       - ./scripts:/docker-entrypoint-initdb.d
#     command: --log-bin=mysql-bin --server-id=1

#   mysql-slave:
#     image: mysql:8.0.33
#     container_name: mysql-slave
#     restart: always
#     env_file: ./slave/.env.slave
#     cap_add:
#       - all
#     environment:
#       - TZ:${TZ}
#       - MYSQL_USER:${MYSQL_USER}
#       - MYSQL_PASSWORD:${MYSQL_PASSWORD}
#       - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}
#       - MYSQL_DATABASE:${MYSQL_DATABASE}
#       - MYSQL_MASTER_HOST:${MYSQL_MASTER_HOST}
#       - MYSQL_MASTER_PORT:${MYSQL_MASTER_PORT}
#       - MYSQL_MASTER_USER:${MYSQL_MASTER_USER}
#       - MYSQL_MASTER_PASSWORD:${MYSQL_MASTER_PASSWORD}
#       - MYSQL_REPLICA_USER:${MYSQL_REPLICA_USER}
#       - MYSQL_REPLICA_PASSWORD:${MYSQL_REPLICA_PASSWORD}
    
#     volumes:
#       - ./slave/data:/var/lib/mysql
#       #- ./slave/my.cnf:/etc/my.cnf
#     #command: --log-bin=mysql-bin --server-id=2 --relay-log=mysql-relay-bin --log-slave-updates=1 --read-only=1 --skip-networking=0 --master-host=${MYSQL_MASTER_HOST} --master-port=${MYSQL_MASTER_PORT} --master-user=${MYSQL_MASTER_USER} --master-password=${MYSQL_MASTER_PASSWORD} --replica-user=${MYSQL_REPLICA_USER} --replica-password=${MYSQL_REPLICA_PASSWORD}



# version: '3'
# services:
#   master:
#     image: mariadb:latest
#     container_name: mariadb-master
#     env_file: ./master/.env.master
#     environment:
#       MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#       MYSQL_DATABASE: ${MYSQL_DATABASE}
#       MYSQL_USER: ${MYSQL_USER}
#       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#       # SERVER_ID: 1
#       # LOG_BIN: mysql-bin
#     volumes:
#       - ./master/data:/var/lib/mysql
#       #- ./scripts:/docker-entrypoint-initdb.d
#     ports:
#       - "3307:3306"
#     command: --log-bin=mysql-bin --server-id=1
#   slave:
#     image: mariadb:latest
#     container_name: mariadb-slave
#     env_file: ./slave/.env.slave
#     environment:
#       MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#       MYSQL_DATABASE: ${MYSQL_DATABASE}
#       MYSQL_USER: ${MYSQL_USER}
#       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#       # SERVER_ID: 2
#       # LOG_BIN: mysql-bin
#       # REPLICATE_DO_DB: db
#       # REPLICATE_IGNORE_TABLE: mysql.*
#     volumes:
#       - ./slave/data:/var/lib/mysql
#     ports:
#       - "3308:3306"
#     command: --log-bin=mysql-bin --server-id=2 --relay-log=mysql-relay-bin --log-slave-updates=1 --read-only=1 --skip-networking=0

# version: '3.7'

# services:
#   db-master:
#     image: mysql:latest
#     container_name: master
#     command: --server-id=1 --log-bin --binlog-do-db=testdb --skip-log-bin-trust-function-creators --binlog-format=ROW
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: masterpass
#       MYSQL_DATABASE: testdb
#     ports:
#       - "3307:3306"
#     volumes:
#       - ./master/data:/var/lib/mysql

#   db-slave:
#     image: mysql:latest
#     container_name: slave
#     command: --server-id=2 --log-bin --binlog-do-db=testdb --skip-log-bin-trust-function-creators --binlog-format=ROW --skip-slave-start
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: slavepass
#       MYSQL_DATABASE: testdb
#       MYSQL_MASTER_HOST: db-master
#       MYSQL_MASTER_PORT: 3307
#       MYSQL_MASTER_USER: root
#       MYSQL_MASTER_PASSWORD: masterpass
#     ports:
#       - "3308:3306"
#     volumes:
#       - ./slave/data:/var/lib/mysql


version: "3.5"
services:
  db_master:
    image: mysql:8.0.30
    container_name: "db_master"
    restart: unless-stopped
    ports:
      - 3307:3306
    volumes:
      - ./master/data:/var/lib/mysql
      - ./master/master.cnf:/etc/my.cnf
    #env_file: ./master/.env.master
    environment:
      # - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      # - MYSQL_USER=${MYSQL_USER}
      # - MYSQL_DATABASE=${MYSQL_DATABASE}
      # - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=cicd@123
      - MYSQL_USER=cicd
      - MYSQL_DATABASE=my_database
      - MYSQL_PASSWORD=cicd@123
    networks:
      - mynetwork
  db_slave:
    image: mysql:8.0.30
    container_name: "db_slave"
    restart: unless-stopped
    depends_on:
      - db_master
    ports:
      - 3308:3306
    volumes:
      - ./slave/data:/var/lib/mysql
      - ./slave/slave.cnf:/etc/my.cnf
    #env_file: ./slave/.env.slave
    environment:
      - MYSQL_ROOT_PASSWORD=cicd@123
      - MYSQL_USER=cicd
      - MYSQL_DATABASE=my_database
      - MYSQL_PASSWORD=cicd@123
    networks:
      - mynetwork
networks:
  mynetwork:
# volumes:
#   /opt/services/mysql/slave/data:
#   /opt/services/mysql/master/data: