# config.yaml
---
replicaCount: 1
image:
  repository: quay.io/prometheusmsteams/prometheus-msteams
  tag: v1.5.1

connectors:
# in alertmanager, this will be used as http://prometheus-msteams:2000/bar
- bar: https://accenture.webhook.office.com/webhookb2/32f1b3d3-603e-45c0-9c55-cf4f5423b440@e0793d39-0939-496d-b129-198edd916feb/IncomingWebhook/d29aabc247db4ce5b9e5253079e27357/d4232cf1-95fa-4ff1-967f-d98d4ff28f23
