version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "90:80"
      - "443:443"
    networks:
      - shinjuku
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt

networks:
 shinjuku:
   name: shinjuku
