- name: Install required packages
  apt:
    name: ['curl', 'tar']

- name: Download Helm
  get_url:
    url: "https://get.helm.sh/helm-v3.7.0-linux-amd64.tar.gz"
    dest: "/tmp/helm.tar.gz"

- name: Extract Helm
  ansible.builtin.unarchive:
    src: "/tmp/helm.tar.gz"
    dest: "/tmp"

- name: Move Helm binary to /usr/local/bin
  ansible.builtin.copy:
    src: "/tmp/linux-amd64/helm"
    dest: "/usr/local/bin/helm"
    mode: '0755'
    owner: root
    group: root

- name: Verify Helm installation
  command: helm version
