- name: Create directories if they do not exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  loop:
    - /opt/services
    - /opt/services/monitoring-stack

- name: Copy files to remote server
  copy:
    src: "files/teams-webhook/"
    dest: "/opt/services/monitoring-stack"
    mode: '0644'

- name: Create monitoring namespace
  k8s:
    api_version: v1
    kind: Namespace
    name: monitoring
    state: present
  ignore_errors: true

- name: Add prometheus-community Helm repository
  helm_repository:
    name: prometheus-community
    repository_url: https://prometheus-community.github.io/helm-charts
  ignore_errors: true

- name: Add prometheus-msteams Helm repository
  helm_repository:
    name: prometheus-msteams
    repository_url: https://prometheus-msteams.github.io/helm-charts
  ignore_errors: true

- name: Update Helm repositories
  helm_repository:
    name: stable
    state: present

- name: Install kube-prometheus-stack
  helm:
    name: kube-prometheus
    chart_reference: prometheus-community/kube-prometheus-stack
    namespace: monitoring
  values_files:
    - /opt/services/monitoring-stack/config.yaml

- name: Install prometheus-msteams
  helm:
    name: prometheus-msteams
    chart_reference: prometheus-msteams/prometheus-msteams
    namespace: monitoring
  values_files:
    - /opt/services/monitoring-stack/config.yaml
