version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    ports:
      - "9030:8080"
      - "8445:8443"
    volumes:
      - jenkins_data:/var/jenkins_home
    environment:
      - JENKINS_OPTS="--httpPort=9030 --httpsPort=8445 --httpsCertificate=/etc/ssl/certs/server.crt --httpsPrivateKey=/etc/ssl/private/server.key"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/services/nginx/www:/usr/share/nginx/html:ro
      - /etc/ssl/certs:/etc/ssl/certs
      - /etc/ssl/private:/etc/ssl/private

volumes:
  jenkins_data:
