apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodeselector
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    disktype: ssd1
---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: nginx-nodeselector2
# spec:
#   nodeName: minikube #schedule pod to specific node
#   containers:
#   - name: nginx
#     image: nginx
#     imagePullPolicy: IfNotPresent
