version: "3"
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    hostname: jenkins
    user: "${UID}:${GID}"
    networks:
      - shinjuku
    ports:
      - "9031:8080"
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
      - JENKINS_ARGS="--prefix=/jenkins"
      - TZ=Asia/Tokyo
    volumes:
      - /opt/services/jenkins_home:/var/jenkins_home
      - /etc/localtime:/etc/localtime
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/bin/docker-compose:/usr/local/bin/docker-compose
      - /usr/lib/jvm:/usr/lib/jvm
      
  agent01:
    container_name: agent01
    image: jenkins/ssh-agent:latest-bullseye-jdk17
    networks:
      - shinjuku
    ports:
      - "3333:22"
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC8sSVXAVxwbCnbag8L94AQWuaP2RojpXKCsYyPs6L8I8yRC8IENZPrAy3tllMCBLlFoScqyFbs/SEE1IeJ+UrBbelCD3L7Ho5zB4TMeobwKyeUbH3bQysdH2/d2J4W8k80/9p8+rM+JEC/yxub+oViyTrjKPwqHKRoXDUzl1ZgdnB2NY7c+jBBOcrXZFrguGEhAwmFvfzyMpYcCorhsziuwqrg4RqCtXyOSrh3l7spbpe1FYg2Aj4ACbDzrQn6V0lbS/wON77axo5A3ued7tppdof4Zlmk6O+KYDblSCZuOo+eLAXdcaBaBPn7tjUxdwxDvpYBiwwkAmbb12ibTKDDjh11k9iq2FBm6bOKQpKROMc9Np2iAApBgRm+ffX/uQt/nyNXuPqLQPw6a4SGtaGyGkNloqXWva9ukjReypsxfRD4q5e6Wfd9J3vt3HMsSkOeubkOdHNT97fW/Si4faQ3OaTe/s5IYVS2gYm+lQxKVU5T1vGrmNxK0pitQ87352E= root@karan-VirtualBox


networks:
 shinjuku:
   name: shinjuku
