version: "3"
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    hostname: jenkins
    user: "${UID}:${GID}"
    networks:
      - shinjuku
    ports:
      - "9031:8080"
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
      - JENKINS_ARGS="--prefix=/jenkins"
      - TZ=Asia/Tokyo
    volumes:
      - /opt/services/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

networks:
 shinjuku:
   name: shinjuku
