version: "3"
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    hostname: jenkins
    user: "${UID}:${GID}"
    # networks:
    #   - shinjuku
    network_mode: "host"
    ports:
      - "9031:8080"
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
      - JENKINS_ARGS="--prefix=/jenkins"
      - TZ=Asia/Tokyo
    volumes:
      - /opt/services/jenkins_home:/var/jenkins_home
      #- /etc/localtime:/etc/localtime
      - /var/run/docker.sock:/var/run/docker.sock
      # - /usr/bin/docker:/usr/bin/docker
      # - /usr/bin/docker-compose:/usr/local/bin/docker-compose
      # - /usr/lib/jvm:/usr/lib/jvm

      
networks:
 shinjuku:
   name: shinjuku
