version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "90:80"
      - "443:443"
    volumes:
      - /opt/services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/nginx/certs/server.crt:/etc/nginx/certs/server.crt
      - /etc/nginx/certs/server.key:/etc/nginx/certs/server.key
      
