- name: Create JDK installation directory
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt
    - /opt/services
    - /opt/services/jdk
    - /opt/services/jdk/java

- name: Download Oracle JDK binary
  get_url:
    url: "https://download.oracle.com/java/{{ jdk_version }}/latest/jdk-{{ jdk_version }}_linux-x64_bin.tar.gz"
    dest: "/opt/services/jdk/jdk-{{ jdk_version }}_linux-x64_bin.tar.gz"


- name: Extract Java archive
  unarchive:
    src: /opt/services/jdk/jdk-{{ jdk_version }}_linux-x64_bin.tar.gz
    dest: /opt/services/jdk/java
    remote_src: yes

- name: Set JAVA_HOME environment variable
  lineinfile:
    dest: /etc/environment
    line: 'JAVA_HOME=/opt/services/jdk/java/jdk-{{ jdk_major_version }}/'
    state: present
    
- name: Set Java executable path
  lineinfile:
    dest: /etc/profile
    line: 'export PATH=$PATH:/opt/services/jdk/java/jdk-{{ jdk_major_version }}/bin'
    state: present


# - name: Add JDK bin directory to PATH
#   lineinfile:
#     dest: ~/.bashrc
#     regexp: '^export PATH=\$PATH:/opt/services/jdk/java/jdk-{{ jdk_major_version }}/bin$'
#     line: 'export PATH=$PATH:/opt/services/jdk/java/jdk-{{ jdk_major_version }}/bin'
#     state: present
#     create: yes


- name: Reload environment variables
  shell: export JAVA_HOME=/opt/services/jdk/java/jdk-{{ jdk_major_version }} && export PATH=$PATH:/opt/services/jdk/java/jdk-{{ jdk_major_version }}/bin
