- name: Create JDK installation directory
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt
    - /opt/services
    - /opt/services/jdk
    - /opt/services/jdk/java

- name: Download Oracle JDK binary
  get_url:
    url: "https://download.oracle.com/java/{{ jdk_version }}/latest/jdk-{{ jdk_version }}_linux-x64_bin.tar.gz"
    dest: "/opt/services/jdk/jdk-{{ jdk_version }}_linux-x64_bin.tar.gz"

- name: Extract Java archive
  unarchive:
    src: "/opt/services/jdk/jdk-{{ jdk_version }}_linux-x64_bin.tar.gz"
    dest: "/opt/services/jdk/java"
    remote_src: yes
  
- name: Set the path
  include_role:
    name: envpath
  vars:
    environment_conf:
      JAVA_HOME: "/opt/services/jdk/java/jdk-{{ jdk_major_version }}"
      PATH: "$JAVA_HOME:$JAVA_HOME/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    environment_file: "/home/{{ ansible_user }}/.bashrc"
    environment_file_2: "/home/{{ ansible_user }}/.bash_profile"
    environment_file_3: "/etc/profile"
    environment_file_4: "/etc/environment"
    bash_profile_path: "../../../roles/jdk/tasks/.bash_profile"
  
    




