apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: mongo
type: Opaque
data:
  username: cm9vdA==   # base64 encoded value of "root"
  password: ZXhhbXBsZQ==   # base64 encoded value of "example"
