---
- name: Stop Artifactory using Docker Compose
  hosts: local
  gather_facts: no
 
  tasks:
    - name: Stop Docker Compose stack
      community.docker.docker_compose:
        project_src: /opt/services/artifactory
        state: absent
        files:
          - docker-compose.yml
          
    - name: Delete /opt/services/artifactory directories
      become: yes
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /opt/services/artifactory