- name: Set up Gitlab using Docker Compose
  hosts: local
  gather_facts: no
  tasks:
    - name: Create /opt/services/gitlab directories if they do not exist
      become: true
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /opt/services
        - /opt/services/gitlab
        - /opt/services/gitlab_home
        - /opt/services/gitlab_home/config
        - /opt/services/gitlab_home/logs
        - /opt/services/gitlab_home/data
        - /opt/services/gitlab_home/gitlab-runner

    - name: Copy Docker Compose file to remote server
      become: yes
      copy:
        src: ../gitlab/docker-compose.yml
        dest: /opt/services/gitlab/docker-compose.yml

    - name: Start gitlab container
      community.docker.docker_compose:
        project_src: /opt/services/gitlab
        files:
          - docker-compose.yml
          
#    - name: Retrieve Gitlab initial admin password
#      become: yes
#      shell: |
#       docker exec -it gitlab-ce grep 'Password:' /etc/gitlab/initial_root_password
#      register: initial_password

#    - name: Print Gitlab initial admin password
#      debug:
#        var: initial_password.stdout

