---
- name: Install Docker
  hosts: azure_vms
  become: true
  vars:
    docker_apt_repo_key_url: https://download.docker.com/linux/ubuntu/gpg
    docker_apt_repo_url: https://download.docker.com/linux/{{ ansible_distribution | lower }}
    docker_macos_pkg_url: https://download.docker.com/mac/stable/Docker.dmg
  tasks:
    - name: Install required packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
      when: ansible_distribution in ['Debian', 'Ubuntu']

    - name: Add Docker APT repository key
      apt_key:
        url: "{{ docker_apt_repo_key_url }}"
      when: ansible_distribution in ['Debian', 'Ubuntu']

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64] {{ docker_apt_repo_url }} {{ ansible_lsb.codename }} stable"
        state: present
      when: ansible_distribution in ['Debian', 'Ubuntu']

    - name: Install Docker on Ubuntu or Debian
      package:
        name: "{{ item }}"
        state: present
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      when: ansible_distribution in ['Debian', 'Ubuntu']

    - name: Install Docker on macOS
      homebrew:
        name: docker
        state: latest
      when: ansible_distribution == 'MacOSX'
      vars:
        homebrew_packages:
          - docker
