- hosts: azure_vms
  become: yes
  vars:
    domain_name: cicd-demo-v1.eastus.cloudapp.azure.com
    email: karan.takalkar@accenture.com
  tasks:
    - name: Install Let's Encrypt client
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - certbot
        - python3-certbot-nginx
    
    - name: Create directory
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /var
        - /var/www
        - /var/www/html
        - /etc/nginx
        - /etc/nginx/certs

    - name: Generate SSL certificates using Let's Encrypt
      become: yes
      command: certbot certonly --nginx -d "{{ domain_name }}" --agree-tos --email "{{ email }}" --non-interactive --redirect --hsts --uir
      args:
        creates: "/etc/letsencrypt/live/{{ domain_name }}"

    # - name: Copy SSL certificates to directory
    #   copy:
    #     src: "/etc/letsencrypt/live/{{ domain_name }}"
    #     dest: "/etc/nginx/certs/"
    #     remote_src: yes


  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
