---
- name: Install and start Jenkins and Nginx containers with SSL
  hosts: local
  gather_facts: false

  tasks:
    - name: Create directory for Nginx config and content
      become: yes
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /opt/services
        - /opt/services/nginx
        - /opt/services/nginx/www
        - /etc/ssl/certs
        - /etc/ssl/private

    - name: Generate SSL certificate and private key
      openssl_privatekey:
        path: /etc/ssl/private/server.key
        mode: 0600
      notify:
        - Generate SSL certificate
    - name: Generate SSL certificate
      openssl_certificate:
        path: /etc/ssl/certs/server.crt
        privatekey_path: /etc/ssl/private/server.key
        common_name: jenkins.example.com
        mode: 0644

    - name: Copy Nginx config file to remote server
      copy:
        src: ../nginx/nginx.conf
        dest: /opt/services/nginx/nginx.conf

    - name: Copy Docker Compose file to remote server
      copy:
        src: ../nginx/docker-compose.yml
        dest: /opt/services/nginx/docker-compose.yml

    - name: Start Jenkins and Nginx containers
      community.docker.docker_compose:
        project_src: /opt/services/nginx
        files:
          - docker-compose.yml
