- name: Install and start Nginx containers
  hosts: local
  gather_facts: false

  tasks:
    - name: Create directory for Nginx config and content
      become: yes
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /opt/services
        - /opt/services/nginx
        - /opt/services/nginx/www
#        - /opt/services/nginx/ssl
#        - /opt/services/nginx/ssl/certs     
#        - /etc/nginx/certs         

    - name: Copy Nginx config file to remote server
      become: yes
      copy:
        src: ../nginx_gateway/nginx.conf
        dest: /opt/services/nginx/nginx.conf

    - name: Copy Docker Compose file to remote server
      become: yes
      copy:
        src: ../nginx_gateway/docker-compose.yml
        dest: /opt/services/nginx/docker-compose.yml

    - name: Start Nginx containers
      become: yes
      community.docker.docker_compose:
        project_src: /opt/services/nginx
        files:
          - docker-compose.yml
