- name: Stop Nginx containers
  hosts: local
  gather_facts: false

  tasks:
    - name: Stop Nginx containers
      become: yes
      community.docker.docker_compose:
        project_src: /opt/services/nginx
        state: absent
        files:
          - docker-compose.yml


    
