- name: Generate SSL key and certificate
  hosts: local
  become: true

  tasks:
    - name: Create directory for SSL certificates
      file:
        path: /etc/nginx/certs
        state: directory
        mode: '0755'

    - name: Generate private key
      openssl_privatekey:
        path: /etc/nginx/certs/server.key
        size: 2048

    - name: Generate certificate signing request (CSR)
      openssl_csr:
        path: /etc/nginx/certs/server.csr
        privatekey_path: /etc/nginx/certs/server.key
        common_name: jenkins
        country_name: JP
        state_or_province_name: Tokyo
        locality_name: Edogawa
        organization_name: Accenture
        email_address: bathlaanjali09@gmail.com

    - name: Generate self-signed certificate
      openssl_certificate:
        path: /etc/nginx/certs/server.crt
        privatekey_path: /etc/nginx/certs/server.key
        csr_path: /etc/nginx/certs/server.csr
        provider: selfsigned
