apiVersion: v1
kind: Pod
metadata:
   name: auto-testing-api
spec:
   containers:
   - name: auto-testing-api
     image: karantakalkar/auto-testing-api
     env:
     - name: DB_HOST
       value: mongo-service
     - name: DB_PORT
       value: "27017"
     - name: DB_USER
       value: "root"
     - name: DB_PASS
       value: "example"
     - name: DB_NAME
       value: "?replicaSet=MainRepSet"
     ports:
     - containerPort: 3000

